export const MODULO_CUMPLIMIENTO = {
  id: 'cumplimiento', orden: 11, titulo: 'Cumplimiento: del criterio a la acción', duracionMin: 4, audioActualizado: true,
  intro: {
    texto: 'Aprende a revisar cada actividad antes de marcarla: qué hacer, qué evitar, un ejemplo y la evidencia que necesitas. Abre una ayuda sin modificar el checklist y distingue los registros manuales de los cálculos automáticos.',
    voz: 'Vamos a revisar cómo se cumple cada actividad. <break time="0.4s"/> Marcar una casilla tiene que respaldar algo que hiciste. <break time="0.4s"/> Ahora tienes una ayuda al lado de cada criterio, con un ejemplo y qué debes evitar. <break time="0.5s"/> Vamos a abrir una. <break time="0.3s"/> Durante este recorrido no necesitas cambiar respuestas ni guardar el checklist.',
  },
  inicio: { ruta: '/centro/{id}/cumplimiento' },
  pasos: [
    { id: 'cu-1', tipo: 'mostrar', target: 'cumplimiento.periodo', titulo: 'Revisa el periodo', texto: 'Confirma el trimestre y el año. Las pestañas de abajo eligen el mes. La evidencia tiene que corresponder al periodo que estás revisando.', voz: 'Empieza por el periodo. <break time="0.4s"/> Confirma el trimestre, el año y después el mes. <break time="0.4s"/> La evidencia tiene que corresponder a ese periodo. <break time="0.4s"/> Una actividad realizada en otro mes no demuestra que hayas cumplido este.' },
    { id: 'cu-2', tipo: 'mostrar', target: 'cumplimiento.producto', titulo: 'Las metas salen de los datos', texto: 'Ventas, deserción y cobranza se calculan desde la base. Sus ayudas explican qué revisar. Si hay un error, corrige el registro de origen.', voz: 'Estas metas se calculan desde los datos. <break time="0.4s"/> Ventas, deserción y cobranza. <break time="0.4s"/> Abajo están las actividades que registras. <break time="0.5s"/> Hacer esas actividades ayuda, pero no sustituye el resultado. <break time="0.4s"/> Si una meta tiene un dato equivocado, revisa y corrige el registro de origen.' },
    { id: 'cu-3', tipo: 'hazlo', target: 'cumplimiento.abrir-ayuda', titulo: 'Abre una ayuda', texto: 'Pulsa Cómo cumplir en Asistencia con días trabajados. Solo abrirás información; las respuestas Sí y No conservan su valor.', voz: 'Busca Asistencia con días trabajados. <break time="0.4s"/> Y pulsa Cómo cumplir. <break time="0.4s"/> Ese botón abre la explicación de la actividad. <break time="0.4s"/> No cambia tu respuesta ni guarda datos del checklist.' },
    { id: 'cu-4', tipo: 'mostrar', target: 'cumplimiento.ayuda', titulo: 'Del ejemplo a la evidencia', texto: 'Lee qué hacer, el ejemplo y qué evitar. Comprueba la evidencia antes de marcar. Cada ficha incluye un audio que puedes escuchar cuando lo necesites.', voz: 'Aquí tienes los pasos, un ejemplo y lo que debes evitar. <break time="0.4s"/> Fíjate en la evidencia que necesitas comprobar. <break time="0.4s"/> En asistencia: fechas reales, ausencias y seguimiento. <break time="0.5s"/> Cada ficha también tiene su audio. <break time="0.4s"/> No hace falta memorizarlo todo: vuelve a la ayuda cuando tengas una duda.' },
    { id: 'cu-5', tipo: 'mostrar', target: 'cumplimiento.guardar', titulo: 'Registra lo que puedes demostrar', texto: 'Comprueba la evidencia, marca los criterios manuales y guarda. Desde septiembre de 2026, Encuestas de satisfacción se completa automáticamente con difusión y participación. Ahora termina el recorrido sin guardar.', voz: 'Cuando trabajes el checklist, primero verifica lo que hiciste. <break time="0.4s"/> Después marcas los criterios manuales y guardas. <break time="0.5s"/> Desde septiembre de dos mil veintiséis, la encuesta mensual a familias se completa de forma automática. <break time="0.4s"/> Necesita difusión registrada y al menos el treinta por ciento de respuestas. <break time="0.4s"/> Ahora termina el recorrido. <break time="0.3s"/> Para aprender no necesitas cambiar ni guardar nada.' },
  ],
  quiz: [
    { pregunta: 'Abres Cómo cumplir en una actividad. ¿Qué cambia?', opciones: ['La actividad se marca Sí', 'Se muestra la guía y las respuestas se mantienen', 'Se guarda el mes', 'Se borra el registro anterior'], explicacion: 'Cómo cumplir abre información. No modifica ni guarda las respuestas del checklist.' },
    { pregunta: 'Convocaste la reunión mensual, pero todavía no se realizó. ¿La marcas como hecha?', opciones: ['Sí, porque ya envié la fecha', 'Sí, si tengo la invitación', 'No: debe realizarse y dejar acuerdos con responsable y fecha'], explicacion: 'La convocatoria prepara la actividad. La evidencia de cumplimiento es la reunión realizada y sus acuerdos.' },
    { pregunta: 'Todas las actividades están realizadas, pero fallas una meta de producto. ¿Qué haces?', opciones: ['Revisar el dato y trabajar la causa: las actividades no compensan la meta', 'Cambiar la meta a Sí', 'Abrir la ayuda para que cambie el semáforo', 'Guardar varias veces hasta que se ponga verde'], explicacion: 'Las metas de producto se calculan desde los datos. La disciplina ayuda a lograrlas, pero no sustituye el resultado.' },
  ],
  errores: [
    { sintoma: 'Abrí la ayuda y mi actividad sigue en No.', causa: 'La ayuda solo explica el proceso.', arreglo: 'Realiza la actividad, comprueba su evidencia y después registra la respuesta si el criterio es manual.' },
    { sintoma: 'Tengo una actividad anunciada y no sé si está cumplida.', causa: 'Una convocatoria no demuestra que se realizó.', arreglo: 'Consulta el ejemplo y la evidencia de ese criterio; registra lo que realmente se hizo en el periodo.' },
  ],
}
