export const MODULO_ENCUESTAS = {
  id:'encuestas',orden:10,titulo:'Encuestas: escucha a tus familias',duracionMin:4,audioActualizado:true,
  intro:{texto:'Prepara la encuesta mensual, comparte el enlace o descarga el QR, revisa la participación y convierte las respuestas en una acción para tu FODA. El criterio se completa con evidencia: difusión registrada y más del 50% de los niños activos del corte.',
    voz:'Vamos a escuchar a tus familias. <break time="0.4s"/> La encuesta tiene un propósito: saber qué está funcionando <break time="0.3s"/> y qué está haciendo que un padre piense en irse. <break time="0.5s"/> Tú compartes el enlace o descargas el código cu erre. <break time="0.4s"/> Pero eso es apenas el comienzo. <break time="0.4s"/> Para completar el mes tiene que responder MÁS de la mitad de tus niños activos. <break time="0.5s"/> Después miras las respuestas, <break time="0.3s"/> escoges una mejora concreta <break time="0.3s"/> y la llevas al FODA. <break time="0.5s"/> Vamos a ver dónde se hace.'},
  inicio:{ruta:'/centro/{id}/encuestas'},
  pasos:[
    {id:'en-1',tipo:'mostrar',target:'encuestas.panel',titulo:'Una encuesta por centro y mes',texto:'Cada centro tiene su encuesta mensual. En el cierre de nivel, pide a los padres responder antes de salir. En este recorrido solo miramos; no necesitas copiar ni enviar nada.',voz:'Aquí tienes la encuesta de tu centro. <break time="0.4s"/> Cada mes comienza una nueva. <break time="0.4s"/> Durante el cierre de nivel, pide a los padres responder antes de salir. <break time="0.5s"/> Hoy solo miramos. <break time="0.3s"/> No hace falta enviar nada para terminar este recorrido.'},
    {id:'en-2',tipo:'mostrar',target:'encuestas.compartir',titulo:'Copiar enlace o descargar cartel PDF',texto:'Descargar cartel PDF con QR prepara una hoja ALOHA en Carta o A4, con centro, mes y llamado a responder. Imprime a tamaño real y renueva el cartel cada mes. La primera copia o descarga crea la encuesta y guarda el corte de activos. Comparte por mensaje directo con cada representante; no abras grupos de WhatsApp. Repetir la copia mantiene el mismo enlace durante el mes.',voz:'Copiar enlace. <break time="0.3s"/> O descargar el código cu erre. <break time="0.4s"/> La primera vez se prepara la encuesta y se guarda la lista de activos. <break time="0.4s"/> Esa lista queda fija este mes. <break time="0.4s"/> Comparte por mensaje directo con cada representante. <break time="0.4s"/> No abras grupos de WhatsApp. <break time="0.4s"/> Si vuelves a copiar, sigue siendo la misma encuesta.'},
    {id:'en-3',tipo:'mostrar',target:'encuestas.progreso',titulo:'Más de la mitad, de verdad',texto:'La meta es más del 50%: si hay 148 niños activos en el corte, hacen falta 75 respuestas. Cada niño cuenta una sola vez, aunque vuelvan a enviar. Copiar el enlace sin respuestas no completa el mes.',voz:'Mira este número. <break time="0.4s"/> Si tienes ciento cuarenta y ocho niños activos, <break time="0.3s"/> necesitas setenta y cinco respuestas. <break time="0.5s"/> Setenta y cuatro es la mitad. <break time="0.3s"/> Y la meta es MÁS de la mitad. <break time="0.4s"/> Cada niño cuenta una sola vez. <break time="0.4s"/> Copiar el enlace sin conseguir respuestas no completa el mes.'},
    {id:'en-4',tipo:'mostrar',target:'encuestas.individuales',titulo:'Una respuesta por niño',texto:'El enlace general valida el nombre completo del niño y el teléfono registrado. Si falta el teléfono o los datos no coinciden, abre esta lista y copia el enlace individual del niño para su representante. Una familia con dos hijos puede responder por cada uno.',voz:'El enlace general valida la ficha con el nombre del niño y el teléfono registrado. <break time="0.4s"/> Si falta el teléfono, no dejes al padre por fuera. <break time="0.4s"/> Aquí tienes el enlace individual de cada niño. <break time="0.4s"/> Se lo pasas solo a su representante. <break time="0.4s"/> Una familia con dos hijos puede responder una vez por cada uno.'},
    {id:'en-5',tipo:'mostrar',target:'encuestas.cumplimiento',titulo:'Cumplimiento se marca solo',texto:'Cuando existe una copia o descarga registrada y se alcanza la meta de respuestas, Encuestas de satisfacción se marca Hecho en el mes correspondiente. La casilla ya no se cambia manualmente.',voz:'Cuando queda registrada la copia o descarga, <break time="0.3s"/> y responde más de la mitad, <break time="0.3s"/> Cumplimiento se marca solo. <break time="0.5s"/> No hay una casilla para aprobarte a mano. <break time="0.4s"/> Al cambiar el mes necesitas una nueva encuesta. <break time="0.4s"/> Las respuestas anteriores quedan en su historial.'},
    {id:'en-6',tipo:'mostrar',target:'encuestas.resultados',titulo:'La respuesta tiene que producir una mejora',texto:'Participación es cuántos niños tienen respuesta. Satisfacción es el porcentaje de respuestas generales con 4 o 5 de 5. Revisa los comentarios y lleva una acción concreta al FODA, que muestra los resultados del trimestre.',voz:'Ojo: participación y satisfacción son dos cosas distintas. <break time="0.4s"/> Una dice cuántos respondieron. <break time="0.4s"/> La otra dice cómo valoraron la experiencia. <break time="0.5s"/> Lee los comentarios. <break time="0.3s"/> Escoge qué vas a mejorar, quién lo hace y para cuándo. <break time="0.4s"/> Eso es lo que llevas al FODA. <break time="0.5s"/> Escuchar sirve cuando después haces algo con lo que te dijeron.'},
  ],
  quiz:[
    {pregunta:'Con 148 activos en el corte y el enlace copiado, ¿cuántas respuestas completan el mes?',opciones:['74: exactamente la mitad','75: más de la mitad','Una respuesta basta','148: deben responder todos'],explicacion:'Más del 50% es una mayoría estricta: 75 de 148. Además debe existir copia o descarga registrada.'},
    {pregunta:'El padre no puede validar su teléfono en el enlace general. ¿Qué haces?',opciones:['Respondes por él','Cambias la meta del mes','Le compartes el enlace individual de su niño','Marcas la encuesta como hecha'],explicacion:'El enlace individual permite responder sin capturar nombre y teléfono. Se comparte solo con el representante de ese niño.'},
    {pregunta:'Ya alcanzaste la participación, pero las opiniones son negativas. ¿Qué sigue?',opciones:['Revisar comentarios y llevar una mejora concreta al FODA','Borrar las respuestas negativas','Volver a copiar el enlace para subir satisfacción','Dar el proceso por terminado'],explicacion:'Completar la participación no garantiza satisfacción. Los resultados y comentarios deben producir una mejora concreta.'},
  ],
  errores:[
    {sintoma:'Copié el enlace y la casilla sigue pendiente.',causa:'Faltan respuestas válidas para superar el 50% de los niños del corte.',arreglo:'Revisa cuántas faltan y comparte los enlaces individuales con los representantes pendientes.'},
    {sintoma:'Un representante recibe un error al validar sus datos.',causa:'El nombre o teléfono no coincide con la ficha, o hay fichas con datos iguales.',arreglo:'Revisa el niño en la lista y comparte solo con su representante el enlace individual.'},
  ],
}
