export const MODULO_PETICIONES = {
  id: 'peticiones', orden: 12, titulo: 'Peticiones: proveedor aprobado del centro', duracionMin: 3, audioActualizado: true,
  intro: {
    texto: 'Si tu centro ya tiene un proveedor aprobado para un servicio, registra su nombre y envía la petición al coordinador operativo. Aprende a distinguir la aprobación del proveedor de la autorización para realizar el trabajo.',
    voz: 'Tu centro puede tener un proveedor aprobado. <break time="0.4s"/> Eso simplifica la petición. <break time="0.4s"/> Escribes su nombre y explicas qué servicio necesitas. <break time="0.5s"/> Pero el trabajo todavía necesita la aprobación del coordinador operativo. <break time="0.4s"/> Vamos a ver dónde se hace, sin enviar ninguna solicitud.',
  },
  inicio: { ruta: '/centro/{id}/foda' },
  pasos: [
    { id: 'pe-1', tipo: 'mostrar', target: 'peticiones.panel', titulo: 'Comentarios y peticiones', texto: 'En FODA encuentras este panel. Un comentario deja información; una petición solicita una decisión sobre una necesidad del centro.', voz: 'En FODA tienes los comentarios y las peticiones. <break time="0.4s"/> El comentario deja información. <break time="0.4s"/> La petición pide una decisión sobre algo que necesita el centro.' },
    { id: 'pe-2', tipo: 'hazlo', target: 'peticiones.abrir', titulo: 'Abre Petición', texto: 'Pulsa Petición. Abrir el formulario no guarda ni envía nada.', voz: 'Pulsa Petición. <break time="0.4s"/> Solo vas a abrir el formulario. <break time="0.4s"/> No hace falta escribir ni enviar nada durante este recorrido.' },
    { id: 'pe-3', tipo: 'mostrar', target: 'peticiones.proveedor', titulo: 'Proveedor que el centro ya tiene aprobado', texto: 'Marca esta opción únicamente si el centro ya cuenta con proveedor aprobado. En ese caso, escribe su nombre; no se exigen cotizaciones ni documentos del proveedor.', voz: 'Esta opción es para un proveedor que el centro YA tiene aprobado. <break time="0.4s"/> Al marcarla, escribes su nombre. <break time="0.4s"/> No necesitas adjuntar cotizaciones ni documentos del proveedor. <break time="0.5s"/> Si todavía no tienes uno aprobado, sigues con las tres cotizaciones.' },
    { id: 'pe-4', tipo: 'mostrar', target: 'peticiones.formulario', titulo: 'Explica el servicio', texto: 'Selecciona la categoría y describe el servicio necesario. Puedes guardar un borrador o enviar a aprobación cuando estén completos el nombre, la categoría y la descripción.', voz: 'Selecciona la categoría y describe el servicio que necesitas. <break time="0.4s"/> Por ejemplo: reparar el aire acondicionado del salón. <break time="0.5s"/> Puedes guardar un borrador. <break time="0.3s"/> Cuando esté completo, envías la petición a aprobación.' },
    { id: 'pe-5', tipo: 'mostrar', target: 'peticiones.panel', titulo: 'Espera la decisión del coordinador', texto: 'Enviar no aprueba el servicio. El coordinador operativo decide en sus centros asignados y la petición conserva el nombre del proveedor. Termina el recorrido sin enviar datos de práctica.', voz: 'Enviar NO aprueba el servicio. <break time="0.5s"/> El coordinador operativo revisa la petición de su centro y decide. <break time="0.4s"/> El nombre del proveedor queda en el registro. <break time="0.5s"/> Ahora termina el recorrido. <break time="0.3s"/> No envíes una petición de práctica.' },
  ],
  quiz: [
    { pregunta: 'Tu centro ya tiene proveedor aprobado. ¿Qué datos del proveedor exige esta opción?', opciones: ['Su nombre', 'Tres PDFs nuevos', 'Su identificación fiscal y dos certificaciones'], explicacion: 'Con proveedor previamente aprobado, se registra solo su nombre. La categoría y descripción explican el servicio solicitado.' },
    { pregunta: 'Enviaste una petición con proveedor aprobado. ¿Puedes asumir que el trabajo quedó autorizado?', opciones: ['Sí, la casilla aprueba el trabajo', 'No: falta la decisión del coordinador operativo', 'Sí, si guardé primero el borrador'], explicacion: 'Que el proveedor ya esté aprobado no autoriza automáticamente un nuevo servicio.' },
    { pregunta: 'El centro todavía no tiene proveedor aprobado. ¿Qué corresponde?', opciones: ['Marcar la opción para avanzar', 'Poner cualquier nombre', 'Presentar las tres cotizaciones de proveedores fiscales distintos'], explicacion: 'La modalidad documental conserva sus requisitos cuando no existe un proveedor previamente aprobado.' },
  ],
  errores: [
    { sintoma: 'No se habilita Enviar a aprobación.', causa: 'Falta el nombre del proveedor, la categoría o la descripción.', arreglo: 'Completa los tres datos. Si usas cotizaciones, comprueba que haya tres válidas.' },
    { sintoma: 'La petición sigue pendiente aunque el proveedor ya estaba aprobado.', causa: 'La aprobación del proveedor y la autorización del servicio son decisiones distintas.', arreglo: 'Espera a que el coordinador operativo revise y apruebe la petición.' },
  ],
}
