export const MODULO_PETICIONES = {
  id: 'peticiones', orden: 12, titulo: 'Peticiones: proveedor aprobado del centro', duracionMin: 3, audioActualizado: true,
  intro: {
    texto: 'Si tu centro ya tiene un proveedor aprobado para un servicio, registra su nombre, adjunta la cotización del servicio en PDF y envía la petición al coordinador operativo. Aprende a distinguir la aprobación del proveedor de la autorización para realizar el trabajo.',
    voz: 'Tu centro puede tener un proveedor aprobado. <break time="0.4s"/> Eso simplifica la petición. <break time="0.4s"/> Escribes su nombre, explicas qué servicio necesitas y adjuntas su cotización en PDF. <break time="0.5s"/> Pero el trabajo todavía necesita la aprobación del coordinador operativo. <break time="0.4s"/> Vamos a ver dónde se hace, sin enviar ninguna solicitud.',
  },
  inicio: { ruta: '/centro/{id}/foda' },
  pasos: [
    { id: 'pe-1', tipo: 'mostrar', target: 'peticiones.panel', titulo: 'Comentarios y peticiones', texto: 'En FODA encuentras este panel. Un comentario deja información; una petición solicita una decisión sobre una necesidad del centro.', voz: 'En FODA tienes los comentarios y las peticiones. <break time="0.4s"/> El comentario deja información. <break time="0.4s"/> La petición pide una decisión sobre algo que necesita el centro.' },
    { id: 'pe-2', tipo: 'hazlo', target: 'peticiones.abrir', titulo: 'Abre Petición', texto: 'Pulsa Petición. Abrir el formulario no guarda ni envía nada.', voz: 'Pulsa Petición. <break time="0.4s"/> Solo vas a abrir el formulario. <break time="0.4s"/> No hace falta escribir ni enviar nada durante este recorrido.' },
    { id: 'pe-3', tipo: 'mostrar', target: 'peticiones.proveedor', titulo: 'Proveedor que el centro ya tiene aprobado', texto: 'Marca esta opción únicamente si el centro ya cuenta con proveedor aprobado. En ese caso, escribe su nombre y adjunta una cotización del servicio en PDF. No hace falta volver a registrar sus datos fiscales.', voz: 'Esta opción es para un proveedor que el centro YA tiene aprobado. <break time="0.4s"/> Al marcarla, escribes su nombre. <break time="0.4s"/> Debes adjuntar UNA cotización del servicio en PDF. <break time="0.5s"/> Si todavía no tienes uno aprobado, sigues con las tres cotizaciones.' },
    { id: 'pe-4', tipo: 'mostrar', target: 'peticiones.formulario', titulo: 'Describe y adjunta la cotización', texto: 'Selecciona la categoría y describe el servicio necesario. Pulsa Continuar: adjuntar cotización y carga el PDF, de hasta 10 MB. Enviar a aprobación se habilita cuando el archivo está validado y los datos están completos.', voz: 'Selecciona la categoría y describe el servicio que necesitas. <break time="0.4s"/> Por ejemplo: reparar el aire acondicionado del salón. <break time="0.5s"/> Pulsa Continuar: adjuntar cotización. <break time="0.4s"/> Carga el PDF del servicio, de hasta diez megabytes. <break time="0.4s"/> Cuando esté validado, puedes enviar a aprobación.' },
    { id: 'pe-5', tipo: 'mostrar', target: 'peticiones.panel', titulo: 'Espera la decisión del coordinador', texto: 'Enviar no aprueba el servicio. El coordinador operativo decide en sus centros asignados y la petición conserva el nombre del proveedor y la cotización adjunta. Termina el recorrido sin enviar datos de práctica.', voz: 'Enviar NO aprueba el servicio. <break time="0.5s"/> El coordinador operativo revisa la petición de su centro y decide. <break time="0.4s"/> El nombre del proveedor y su cotización quedan en el registro. <break time="0.5s"/> Ahora termina el recorrido. <break time="0.3s"/> No envíes una petición de práctica.' },
  ],
  quiz: [
    { pregunta: 'Tu centro ya tiene proveedor aprobado. ¿Qué debes presentar con esta opción?', opciones: ['Su nombre y una cotización del servicio en PDF', 'Solo su nombre, sin adjuntos', 'Tres PDFs nuevos'], explicacion: 'El proveedor aprobado requiere su nombre y una cotización del servicio en PDF. También debes completar la categoría y la descripción.' },
    { pregunta: 'Enviaste una petición con proveedor aprobado. ¿Puedes asumir que el trabajo quedó autorizado?', opciones: ['Sí, la casilla aprueba el trabajo', 'No: falta la decisión del coordinador operativo', 'Sí, si guardé primero el borrador'], explicacion: 'Que el proveedor ya esté aprobado no autoriza automáticamente un nuevo servicio.' },
    { pregunta: 'El centro todavía no tiene proveedor aprobado. ¿Qué corresponde?', opciones: ['Marcar la opción para avanzar', 'Poner cualquier nombre', 'Presentar las tres cotizaciones de proveedores fiscales distintos'], explicacion: 'La modalidad documental conserva sus requisitos cuando no existe un proveedor previamente aprobado.' },
  ],
  errores: [
    { sintoma: 'No se habilita Enviar a aprobación.', causa: 'Falta el nombre del proveedor, la categoría, la descripción o una cotización válida en PDF.', arreglo: 'Completa los datos y adjunta una cotización válida del proveedor aprobado. Sin proveedor aprobado, se necesitan tres cotizaciones válidas.' },
    { sintoma: 'La petición sigue pendiente aunque el proveedor ya estaba aprobado.', causa: 'La aprobación del proveedor y la autorización del servicio son decisiones distintas.', arreglo: 'Espera a que el coordinador operativo revise y apruebe la petición.' },
  ],
}
