// Inventario explícito de acceso backend. Si una Server Action o Route Handler
// nuevo aparece sin clasificación, test/backend-access-matrix.test.mjs falla.
export const ACCESS_KINDS = Object.freeze({
  public: 'public',
  session: 'session',
  readGlobal: 'readGlobal',
  readCentro: 'readCentro',
  writeCentro: 'writeCentro',
  writeCentroHelper: 'writeCentroHelper',
  deleteCentro: 'deleteCentro',
  closeMonth: 'closeMonth',
  master: 'master',
  usersRead: 'usersRead',
  usersManage: 'usersManage',
  oficio: 'oficio',
  selfTraining: 'selfTraining',
  passwordToken: 'passwordToken',
  coachToken: 'coachToken',
  cron: 'cron',
  uploadCallback: 'uploadCallback',
  signedDownload: 'signedDownload',
})

export const ACTION_ACCESS_MATRIX = Object.freeze({
  'app/actions/auth.js#login': ACCESS_KINDS.public,
  'app/actions/auth.js#logout': ACCESS_KINDS.public,
  'app/actions/auth.js#changePassword': ACCESS_KINDS.session,

  'app/actions/centro.js#getCentroResumen': ACCESS_KINDS.readCentro,
  'app/actions/centro.js#getHistorialCentro': ACCESS_KINDS.readCentro,

  'app/actions/centros.js#listCentros': ACCESS_KINDS.session,
  'app/actions/centros.js#getCentroNombre': ACCESS_KINDS.readCentro,
  'app/actions/centros.js#listCentrosConUsuarios': ACCESS_KINDS.readGlobal,
  'app/actions/centros.js#createCentro': ACCESS_KINDS.master,
  'app/actions/centros.js#updateCentro': ACCESS_KINDS.master,
  'app/actions/centros.js#deleteCentro': ACCESS_KINDS.master,

  'app/actions/coach.js#loadGrupoCoach': ACCESS_KINDS.coachToken,
  'app/actions/coach.js#marcarAsistencia': ACCESS_KINDS.coachToken,
  'app/actions/coach.js#guardarNotaCoach': ACCESS_KINDS.coachToken,
  'app/actions/coach.js#getDesercionPorCoach': ACCESS_KINDS.readCentro,
  // Lee SOLO lo del propio coach (coaches.usuario_id = su sesión): no recibe
  // centro por parámetro, así que no hay alcance ajeno que guardar.
  'app/actions/coach.js#misGruposCoach': ACCESS_KINDS.session,

  'app/actions/cuadro.js#loadCuadro': ACCESS_KINDS.readCentro,
  'app/actions/cuadro.js#savePedido': ACCESS_KINDS.writeCentro,
  'app/actions/cuadro.js#deletePedido': ACCESS_KINDS.deleteCentro,
  'app/actions/cuadro.js#sincronizarConKpi': ACCESS_KINDS.writeCentro,

  'app/actions/cumplimiento.js#loadCumplimiento': ACCESS_KINDS.readCentro,
  'app/actions/cumplimiento.js#getDisciplinaTrimestre': ACCESS_KINDS.readCentro,
  'app/actions/cumplimiento.js#getMetasMarcadas': ACCESS_KINDS.readCentro,
  'app/actions/cumplimiento.js#getMetasMarcadasPanel': ACCESS_KINDS.readGlobal,
  'app/actions/cumplimiento.js#getDiscrepanciasHistoricas': ACCESS_KINDS.readGlobal,
  'app/actions/cumplimiento.js#saveCumplimiento': ACCESS_KINDS.writeCentro,

  'app/actions/dashboard.js#getCentrosKpiRango': ACCESS_KINDS.readGlobal,
  'app/actions/dashboard.js#getCentrosKpi': ACCESS_KINDS.readGlobal,
  'app/actions/dashboard.js#getHistorialAdmin': ACCESS_KINDS.readGlobal,
  'app/actions/dashboard.js#getNinosSerie': ACCESS_KINDS.readGlobal,

  'app/actions/encuestas.js#cargarEncuesta': ACCESS_KINDS.readCentro,
  'app/actions/encuestas.js#prepararEncuesta': ACCESS_KINDS.writeCentroHelper,
  'app/actions/encuestas.js#registrarDifusionEncuesta': ACCESS_KINDS.writeCentroHelper,
  'app/actions/encuestas.js#resumenEncuestasTrimestre': ACCESS_KINDS.readCentro,

  'app/actions/entrenamiento-oficio.js#cargarOficio': ACCESS_KINDS.oficio,
  'app/actions/entrenamiento-oficio.js#resumenOficio': ACCESS_KINDS.oficio,
  'app/actions/entrenamiento-oficio.js#cargarConceptos': ACCESS_KINDS.oficio,
  'app/actions/entrenamiento-oficio.js#guardarConcepto': ACCESS_KINDS.oficio,
  'app/actions/entrenamiento-oficio.js#marcarEstudiado': ACCESS_KINDS.oficio,
  'app/actions/entrenamiento-oficio.js#responderQuizOficio': ACCESS_KINDS.oficio,
  'app/actions/entrenamiento-oficio.js#firmarDrill': ACCESS_KINDS.oficio,
  'app/actions/entrenamiento-oficio.js#quitarFirmaDrill': ACCESS_KINDS.oficio,
  'app/actions/entrenamiento-oficio.js#colaFirmas': ACCESS_KINDS.oficio,
  'app/actions/entrenamiento-oficio.js#contadorFirmas': ACCESS_KINDS.oficio,
  'app/actions/entrenamiento-oficio.js#matrizOficio': ACCESS_KINDS.master,

  'app/actions/entrenamiento.js#cargarProgreso': ACCESS_KINDS.selfTraining,
  'app/actions/entrenamiento.js#resumenProgreso': ACCESS_KINDS.selfTraining,
  'app/actions/entrenamiento.js#marcarTourVisto': ACCESS_KINDS.selfTraining,
  'app/actions/entrenamiento.js#responderQuiz': ACCESS_KINDS.selfTraining,
  'app/actions/entrenamiento.js#matrizProgreso': ACCESS_KINDS.master,
  'app/actions/entrenamiento.js#reiniciarProgreso': ACCESS_KINDS.master,

  'app/actions/estudiantes.js#inscribirEstudiante': ACCESS_KINDS.writeCentro,
  'app/actions/estudiantes.js#actualizarEstudiante': ACCESS_KINDS.writeCentro,
  'app/actions/estudiantes.js#graduarTiny': ACCESS_KINDS.writeCentro,
  'app/actions/estudiantes.js#fijarInicioNivel': ACCESS_KINDS.writeCentro,
  'app/actions/estudiantes.js#fijarInicioNivelLote': ACCESS_KINDS.writeCentro,
  'app/actions/estudiantes.js#sugerenciasAnclaNinos': ACCESS_KINDS.readCentro,
  'app/actions/estudiantes.js#marcarBajaPotencial': ACCESS_KINDS.writeCentro,
  'app/actions/estudiantes.js#revertirBajaPotencial': ACCESS_KINDS.writeCentro,
  'app/actions/estudiantes.js#retirarEstudiante': ACCESS_KINDS.writeCentro,
  'app/actions/estudiantes.js#anularMatricula': ACCESS_KINDS.writeCentro,
  'app/actions/matricula-reversos.js#registrarReversoMatricula': ACCESS_KINDS.writeCentro,
  'app/actions/estudiantes.js#programarRetiro': ACCESS_KINDS.writeCentro,
  'app/actions/estudiantes.js#cancelarRetiroProgramado': ACCESS_KINDS.writeCentro,
  'app/actions/estudiantes.js#reincorporarEstudiante': ACCESS_KINDS.writeCentro,

  'app/actions/eventos.js#eventosConfig': ACCESS_KINDS.public,
  'app/actions/eventos.js#opcionesFormulario': ACCESS_KINDS.readCentro,
  'app/actions/eventos.js#listarEventos': ACCESS_KINDS.readCentro,
  'app/actions/eventos.js#crearEvento': ACCESS_KINDS.writeCentro,
  'app/actions/eventos.js#actualizarEvento': ACCESS_KINDS.writeCentro,
  'app/actions/eventos.js#eliminarEvento': ACCESS_KINDS.deleteCentro,
  'app/actions/eventos.js#duplicarEvento': ACCESS_KINDS.writeCentro,
  'app/actions/eventos.js#listarRegistros': ACCESS_KINDS.readCentro,
  'app/actions/eventos.js#agregarInvitado': ACCESS_KINDS.writeCentro,
  'app/actions/eventos.js#marcarAsistencia': ACCESS_KINDS.writeCentro,
  'app/actions/eventos.js#marcarPago': ACCESS_KINDS.writeCentro,

  'app/actions/foda.js#loadFoda': ACCESS_KINDS.readCentro,
  'app/actions/foda.js#saveFoda': ACCESS_KINDS.writeCentro,

  'app/actions/growth.js#getCentroGrowth': ACCESS_KINDS.readCentro,
  'app/actions/growth.js#getGrowthBriefing': ACCESS_KINDS.readCentro,
  'app/actions/growth.js#markGrowthBriefingShown': ACCESS_KINDS.writeCentro,
  'app/actions/growth.js#acknowledgeGrowthBriefing': ACCESS_KINDS.writeCentro,
  'app/actions/growth.js#snoozeGrowthBriefing': ACCESS_KINDS.writeCentro,
  'app/actions/growth.js#updateGrowthRecommendation': ACCESS_KINDS.writeCentro,
  'app/actions/growth.js#getGrowthAdminOverview': ACCESS_KINDS.readGlobal,

  'app/actions/grupos.js#loadOperaciones': ACCESS_KINDS.readCentro,
  'app/actions/grupos.js#crearGrupo': ACCESS_KINDS.writeCentro,
  'app/actions/grupos.js#actualizarGrupo': ACCESS_KINDS.writeCentro,
  'app/actions/grupos.js#ajustarItinerarioGrupo': ACCESS_KINDS.writeCentro,
  'app/actions/grupos.js#linkCoach': ACCESS_KINDS.writeCentro,
  'app/actions/grupos.js#setInscripcionAbierta': ACCESS_KINDS.writeCentro,
  'app/actions/grupos.js#toggleInscripcionGrupo': ACCESS_KINDS.writeCentro,
  'app/actions/grupos.js#cerrarGrupo': ACCESS_KINDS.writeCentro,
  'app/actions/grupos.js#reabrirGrupo': ACCESS_KINDS.writeCentro,
  'app/actions/grupos.js#siguienteNumero': ACCESS_KINDS.readCentro,
  'app/actions/grupos.js#listarGruposActivos': ACCESS_KINDS.readCentro,
  'app/actions/grupos.js#contarGruposActivos': ACCESS_KINDS.readCentro,
  'app/actions/grupos.js#saveCoach': ACCESS_KINDS.writeCentro,
  'app/actions/grupos.js#toggleCoach': ACCESS_KINDS.writeCentro,
  'app/actions/grupos.js#saveSalon': ACCESS_KINDS.writeCentro,
  'app/actions/grupos.js#toggleSalon': ACCESS_KINDS.writeCentro,
  'app/actions/grupos.js#sugerenciasFusion': ACCESS_KINDS.readCentro,
  'app/actions/grupos.js#aplicarFusion': ACCESS_KINDS.writeCentro,
  'app/actions/grupos.js#extenderVentanaLlenado': ACCESS_KINDS.writeCentro,

  'app/actions/higiene.js#getHigienePendientes': ACCESS_KINDS.readCentro,

  'app/actions/kpi.js#loadKpiMes': ACCESS_KINDS.readCentro,
  'app/actions/kpi.js#saveKpiMes': ACCESS_KINDS.writeCentro,
  'app/actions/kpi.js#cerrarMes': ACCESS_KINDS.closeMonth,
  'app/actions/kpi.js#reabrirMes': ACCESS_KINDS.closeMonth,

  'app/actions/metas.js#getMetas': ACCESS_KINDS.readGlobal,
  'app/actions/metas.js#saveMetas': ACCESS_KINDS.master,

  'app/actions/navigation.js#getNavigationContext': ACCESS_KINDS.session,
  'app/actions/ocupacion.js#getOcupacionCoach': ACCESS_KINDS.readCentro,

  'app/actions/password.js#requestPasswordReset': ACCESS_KINDS.passwordToken,
  'app/actions/password.js#getTokenInfo': ACCESS_KINDS.passwordToken,
  'app/actions/password.js#setPassword': ACCESS_KINDS.passwordToken,

  'app/actions/peticiones.js#listPeticiones': ACCESS_KINDS.readCentro,
  'app/actions/peticiones.js#createComentario': ACCESS_KINDS.writeCentro,
  'app/actions/peticiones.js#updateComentario': ACCESS_KINDS.writeCentro,
  'app/actions/peticiones.js#createPeticionDraft': ACCESS_KINDS.writeCentro,
  'app/actions/peticiones.js#updatePeticionDraft': ACCESS_KINDS.writeCentro,
  'app/actions/peticiones.js#submitPeticion': ACCESS_KINDS.writeCentro,
  'app/actions/peticiones.js#changePeticionStatus': ACCESS_KINDS.writeCentro,
  'app/actions/peticiones.js#discardPeticionDraft': ACCESS_KINDS.writeCentro,
  'app/actions/peticiones.js#eliminarPeticion': ACCESS_KINDS.master,
  'app/actions/peticiones.js#prepareCotizacionUpload': ACCESS_KINDS.writeCentro,
  'app/actions/peticiones.js#getCotizacionUploadStatus': ACCESS_KINDS.readCentro,
  'app/actions/peticiones.js#discardCotizacionAttempt': ACCESS_KINDS.writeCentro,

  'app/actions/public.js#getPublicStats': ACCESS_KINDS.public,

  'app/actions/reservas.js#listarReservas': ACCESS_KINDS.readCentro,
  'app/actions/reservas.js#sugerenciaReserva': ACCESS_KINDS.readCentro,
  'app/actions/reservas.js#guardarReserva': ACCESS_KINDS.writeCentro,
  'app/actions/reservas.js#eliminarReserva': ACCESS_KINDS.deleteCentro,

  'app/actions/usuarios.js#getUsuariosPageData': ACCESS_KINDS.usersRead,
  'app/actions/usuarios.js#createUsuario': ACCESS_KINDS.usersManage,
  'app/actions/usuarios.js#updateUsuario': ACCESS_KINDS.usersManage,
  'app/actions/usuarios.js#reenviarInvitacion': ACCESS_KINDS.usersManage,
  'app/actions/usuarios.js#bloquearUsuario': ACCESS_KINDS.usersManage,
  'app/actions/usuarios.js#desbloquearUsuario': ACCESS_KINDS.usersManage,
  'app/actions/usuarios.js#deleteUsuario': ACCESS_KINDS.usersManage,

  'app/actions/zoho.js#getZohoEstado': ACCESS_KINDS.master,
})

export const API_ACCESS_MATRIX = Object.freeze({
  'app/api/centro/[id]/cuadro/route.js#GET': ACCESS_KINDS.readCentro,
  'app/api/cron/cobranza-zoho/route.js#GET': ACCESS_KINDS.cron,
  'app/api/cron/llenado/route.js#GET': ACCESS_KINDS.cron,
  'app/api/cron/peticiones-cleanup/route.js#GET': ACCESS_KINDS.cron,
  'app/api/encuestas/[token]/route.js#POST': ACCESS_KINDS.public,
  'app/api/peticiones/cotizaciones/[id]/download/route.js#GET': ACCESS_KINDS.signedDownload,
  'app/api/peticiones/cotizaciones/upload/route.js#POST': ACCESS_KINDS.uploadCallback,
  'app/api/zoho/callback/route.js#GET': ACCESS_KINDS.master,
  'app/api/zoho/connect/route.js#GET': ACCESS_KINDS.master,
})
