// El manual aporta el proceso; los ejemplos son orientaciones operativas,
// no nuevas frecuencias ni metas. Las reglas automáticas siguen en el servidor.
const manual = (seccion) => ({ tipo: 'manual', referencia: seccion })
const operativa = { tipo: 'operativa', referencia: 'Guía práctica del checklist del centro' }
const plataforma = { tipo: 'plataforma', referencia: 'Reglas vigentes de KPI ALOHA' }
const voz = (...frases) => frases.join(' <break time="0.4s"/> ')

export const CUMPLIMIENTO_AYUDA = {
  asistencia_dias: {
    como: ['Registra la asistencia en cada clase y los días realmente trabajados; contrasta el registro con el calendario del grupo.', 'Cuando un niño acumule al menos dos ausencias, el coach avisa a la administradora o asistente para hacer seguimiento.'],
    evidencia: 'Calendario y asistencia del periodo, con ausencias identificadas y seguimiento registrado cuando corresponda.',
    ejemplo: 'El grupo tuvo cuatro clases: anotas la asistencia de cada fecha. Un niño faltó a dos; registras el contacto con su representante y el acuerdo de regreso.',
    evitar: ['Completar todo como presente al final del mes sin revisar las clases.', 'Contar una clase cancelada como trabajada o dejar ausencias repetidas sin seguimiento.'],
    fuente: manual('Administradora · Módulo 1: calendario, asistencia y seguimiento de ausencias'),
    voz: voz('Empieza por el calendario del grupo.', 'Registra lo que pasó en cada clase, sin rellenar de memoria al final del mes.', 'Si un niño falta dos veces, hay que avisar y hacer seguimiento.', 'Por ejemplo: cuatro clases, cuatro registros. Y si hubo ausencias, deja el acuerdo con su representante.'),
  },
  seguimiento_evolucion: {
    como: ['Revisa con el coach el avance de cada niño y registra su retroalimentación semanal en la plantilla de ClassDojo.', 'Describe un logro, una dificultad concreta y la acción que van a trabajar; da seguimiento a ese acuerdo.'],
    evidencia: 'Plantilla de retroalimentación del niño actualizada durante el mes, con observaciones y acciones específicas.',
    ejemplo: '“Ya reconoce las unidades. Aún confunde las decenas; esta semana practicaremos ese paso y revisaremos su avance en la siguiente clase.”',
    evitar: ['Copiar “todo bien” para todos los niños.', 'Etiquetar al niño como flojo o limitarse a señalar el error sin explicar cómo ayudarlo.'],
    fuente: manual('Coach · Portafolio digital: retroalimentación semanal'),
    voz: voz('El seguimiento tiene que decir qué está pasando con ese niño.', 'Anota un logro, una dificultad y lo que van a trabajar.', 'Por ejemplo: ya reconoce las unidades, pero necesita practicar las decenas.', 'Decir todo bien, igual para todo el grupo, no permite acompañar su evolución.'),
  },
  ninos_trabajando_study: {
    como: ['Revisa en Study la gráfica de trabajo del grupo y verifica que corresponde a los niños y al periodo que estás evaluando.', 'Identifica quién no registra actividad y consulta al coach para distinguir falta de trabajo, ausencia o un registro pendiente.'],
    evidencia: 'Gráfica del periodo y revisión de los casos sin actividad, con la acción de seguimiento que corresponda.',
    ejemplo: 'La gráfica muestra dos niños sin actividad. Revisas con el coach: uno faltó y requiere seguimiento; el otro trabajó, pero falta cargar su registro.',
    evitar: ['Usar una gráfica de otro mes o de otro grupo.', 'Registrar trabajo que no ocurrió para que la gráfica se vea completa.'],
    fuente: operativa,
    voz: voz('Abre la gráfica del grupo y revisa el periodo.', 'Si hay niños sin actividad, conversa con el coach para saber qué pasó.', 'Puede haber una ausencia, o puede faltar el registro de una clase que sí ocurrió.', 'Corrige la causa. No inventes trabajo para que la gráfica se vea completa.'),
  },
  portafolio: {
    como: ['Comprueba que cada niño tenga su portafolio digital en ClassDojo con la retroalimentación semanal del coach.', 'Incluye los acuerdos con representantes y los refuerzos cuando existan, de manera que se pueda seguir la evolución.'],
    evidencia: 'Portafolios del grupo con entradas del periodo, retroalimentación concreta y acuerdos de seguimiento.',
    ejemplo: 'En el portafolio se ve el ejercicio trabajado, qué logró el niño y qué practicará. Si hubo una reunión, queda registrado el acuerdo.',
    evitar: ['Guardar únicamente fotos sin explicar el avance.', 'Subir la información de un niño al portafolio de otro o publicar comentarios personales en el grupo general.'],
    fuente: manual('Coach · Portafolio digital, retroalimentación y acuerdos con representantes'),
    voz: voz('El portafolio debe contar cómo va avanzando el niño.', 'No basta con subir una foto del ejercicio.', 'Explica qué logró y qué va a practicar después.', 'Si hubo un acuerdo con el representante, déjalo en su portafolio. Y revisa que sea el del niño correcto.'),
  },
  padres_conectados: {
    como: ['Contrasta los representantes de los niños activos con las conexiones de ClassDojo.', 'Ayuda a quienes tienen una invitación pendiente a entrar y comprobar que ven el grupo y el portafolio correctos.'],
    evidencia: 'Listado de conexiones contrastado con los activos y seguimiento de las invitaciones que aún no se aceptaron.',
    ejemplo: 'Hay 12 niños activos y solo 10 representantes conectados. Contactas por separado a los dos pendientes y compruebas el acceso con ellos.',
    evitar: ['Dar por conectado a un padre solo porque enviaste la invitación.', 'Pedir contraseñas personales o conectar a un representante con la ficha equivocada.'],
    fuente: operativa,
    voz: voz('Una invitación enviada todavía no es un padre conectado.', 'Comprueba que pueda entrar y ver el portafolio de su niño.', 'Si faltan dos representantes, acompaña a esos dos hasta resolver el acceso.', 'No pidas sus contraseñas. Ayúdalos a entrar desde su propia cuenta.'),
  },
  clase_padres: {
    como: ['Organiza la clase de padres al iniciar el nivel o, como máximo, en la segunda semana; coordina su realización con la administradora.', 'Registra la asistencia por grupo. A quienes falten, envía el resumen y la invitación a la siguiente convocatoria.'],
    evidencia: 'Convocatoria, registro de asistencia por grupo y seguimiento a los representantes ausentes.',
    ejemplo: 'Al comenzar un grupo convocas a sus representantes. Después de la clase registras quién asistió y envías a los ausentes el resumen y la siguiente fecha.',
    evitar: ['Marcar la actividad como hecha solo por anunciar una fecha.', 'Omitir a los ausentes o repetirla cada mes sin considerar cuándo inicia el nivel.'],
    fuente: manual('Administradora · Módulo 8: clase de padres y comunicación'),
    voz: voz('La clase de padres se organiza al comenzar el nivel, a más tardar en la segunda semana.', 'No se completa solo con publicar la invitación.', 'Realiza la clase, registra quién asistió y da seguimiento a quien faltó.', 'A los ausentes les envías el resumen y la siguiente convocatoria.'),
  },
  coach_activo: {
    como: ['Comprueba que el coach asignado esté atendiendo el grupo y pueda usar las herramientas que necesita para la clase.', 'Revisa su asistencia y el seguimiento del grupo; si hubo una sustitución, verifica quién lo está atendiendo realmente.'],
    evidencia: 'Asignación vigente, asistencia del coach y registros recientes de las clases y del seguimiento de niños.',
    ejemplo: 'El coach titular estuvo ausente. Confirmas que el sustituto impartió las clases, tenía acceso al grupo y dejó el seguimiento correspondiente.',
    evitar: ['Dar por activo al coach únicamente porque su cuenta existe.', 'Dejar al grupo con una asignación desactualizada o sin responsable efectivo.'],
    fuente: operativa,
    voz: voz('Una cuenta creada no demuestra que el grupo esté siendo atendido.', 'Comprueba quién dio las clases y quién dejó el seguimiento.', 'Si hubo una sustitución, revisa que el nuevo coach tenga acceso y conozca los pendientes.', 'Lo que necesitas es un responsable trabajando con el grupo.'),
  },
  niveles_actualizados: {
    como: ['Compara el nivel registrado del grupo y de sus niños con el nivel que realmente están cursando.', 'Revisa las transiciones de nivel y corrige los registros en la herramienta correspondiente cuando el avance esté confirmado.'],
    evidencia: 'Nivel e itinerario vigentes, coherentes con las clases y con los registros de los niños.',
    ejemplo: 'El grupo comenzó el nivel 3, pero todavía aparece en el 2. Confirmas la transición con el coach y actualizas el registro correspondiente.',
    evitar: ['Adelantar un nivel antes de que el grupo lo empiece.', 'Cambiar números para mejorar el reporte sin comprobar el avance real.'],
    fuente: operativa,
    voz: voz('El nivel registrado tiene que coincidir con lo que el grupo está cursando.', 'Si ya comenzó el siguiente nivel, confirma el cambio con el coach y actualiza el registro.', 'No adelantes un nivel porque está previsto para el mes que viene.', 'Primero ocurre el avance. Después lo refleja el sistema.'),
  },
  ninos_activos_study: {
    como: ['Compara el padrón real de niños activos del centro con los niños registrados en Study y su grupo.', 'Resuelve fichas faltantes, duplicadas o mal asignadas; comprueba los retiros y cambios antes de actualizar.'],
    evidencia: 'Conciliación del padrón de activos con Study, con cada niño en su grupo y las diferencias resueltas.',
    ejemplo: 'En el grupo hay 10 activos, pero Study muestra 9. Ubicas la inscripción faltante y verificas que quede en el grupo correcto.',
    evitar: ['Comparar solo los totales: dos errores pueden compensarse.', 'Borrar historiales o mantener retirados como activos para que los números coincidan.'],
    fuente: operativa,
    voz: voz('Compara los niños uno por uno, no solamente el total.', 'Puedes tener diez fichas y aun así tener un niño duplicado y otro que falta.', 'Revisa que cada activo esté en el grupo correcto de Study.', 'Resuelve las diferencias conservando su historial.'),
  },
  encuestas_satisfaccion: {
    como: ['Desde septiembre de 2026, copia el enlace o descarga el QR de la encuesta del mes; esa primera acción registra la difusión y fija el corte de activos.', 'Comparte con los representantes y consigue respuestas válidas de más del 50% de los niños del corte. Revisa las opiniones y lleva una mejora al FODA.'],
    evidencia: 'Panel de encuesta mensual: difusión registrada, respuestas únicas y meta alcanzada. Con ambas condiciones, el criterio se marca automáticamente.',
    ejemplo: 'Si el corte tiene 148 activos, necesitas 75 respuestas y una copia o descarga registrada. Con 74 todavía falta una. Los meses anteriores a septiembre de 2026 conservan su registro manual.',
    evitar: ['Marcar como terminada la encuesta solo por copiar el enlace.', 'Responder por las familias, duplicar respuestas o confundir alta participación con alta satisfacción.'],
    fuente: { tipo: 'plataforma', referencia: 'Encuesta mensual aprobada; manual de Administradora · Módulo 6: encuesta en el cierre de nivel' },
    voz: voz('Copiar el enlace es el comienzo.', 'Desde septiembre de dos mil veintiséis, este criterio funciona de forma automática.', 'Para completar el mes debe responder más de la mitad de los niños activos del corte.', 'Por ejemplo: de ciento cuarenta y ocho, necesitas setenta y cinco respuestas.', 'Con la copia o descarga registrada y la meta alcanzada, se marca solo. Después convierte las opiniones en una mejora.'),
  },
  brochure: {
    como: ['Revisa que el brochure vigente esté disponible y visible en recepción.', 'Confirma que sus datos de contacto y oferta correspondan al centro y que el equipo pueda entregarlo y explicar el siguiente paso.'],
    evidencia: 'Brochure vigente al alcance de los visitantes, con datos correctos y unidades disponibles.',
    ejemplo: 'Una familia pregunta por el programa. Recepción le entrega el brochure vigente y le explica cómo coordinar su clase de prueba.',
    evitar: ['Dejar material guardado donde nadie lo encuentra.', 'Entregar brochures deteriorados, con contactos antiguos o promesas que el centro no ofrece.'],
    fuente: operativa,
    voz: voz('El brochure tiene que estar disponible cuando llega una familia.', 'Revisa que sea la versión vigente y que los datos del centro estén correctos.', 'Entrégalo y explica cómo coordinar la clase de prueba.', 'Tener una caja guardada, fuera del alcance de recepción, no resuelve la atención.'),
  },
  cartel_qr: {
    como: ['Coloca en recepción el cartel con el QR de la ficha correcta del centro en Google.', 'Escanéalo con un teléfono para comprobar que abre la sede correcta y se puede leer sin dificultad.'],
    evidencia: 'Cartel visible y QR probado, dirigido a la ficha de Google de ese centro.',
    ejemplo: 'Escaneas el cartel de Anclas Mall y compruebas que abre su ficha, no la de otra sede. Lo ubicas donde un visitante puede acercar su teléfono.',
    evitar: ['Confundir este QR de Google con el QR de la encuesta mensual.', 'Usar un código roto, diminuto o de otra sede; condicionar la atención a dejar una opinión positiva.'],
    fuente: operativa,
    voz: voz('Este cartel lleva a la ficha del centro en Google.', 'Escanéalo tú primero y comprueba que abra la sede correcta.', 'El código de Google y el de la encuesta mensual tienen destinos distintos.', 'Ponlo donde se pueda leer. Y deja que cada persona opine libremente.'),
  },
  saludo_cordial: {
    como: ['Recibe a cada representante con atención y trato respetuoso, usando usted como indica el manual.', 'Escucha su necesidad y resuélvela o dirígela a la persona responsable; cuida también la despedida.'],
    evidencia: 'Observación de la atención en recepción y seguimiento de consultas o situaciones que necesitaron ayuda.',
    ejemplo: '“Buenos días, señora. Bienvenida a ALOHA. ¿En qué puedo ayudarle?” Si necesita hablar del avance de su hijo, coordinas la conversación con el coach.',
    evitar: ['Ignorar a quien llega por seguir mirando el teléfono.', 'Usar apodos, discutir delante de otras familias o responder sin escuchar la consulta.'],
    fuente: manual('Administradora · Módulo 8: comunicación con representantes, trato de usted'),
    voz: voz('Cuando llega un representante, detén lo que puedas detener y atiéndelo.', 'Saluda con respeto, usando usted.', 'Buenos días, señora. Bienvenida a ALOHA. ¿En qué puedo ayudarle?', 'Escucha y resuelve, o busca a la persona indicada. No lo dejes esperando mientras miras el teléfono.'),
  },
  fotos_grupo: {
    como: ['Coordina fotos actuales de la actividad del grupo y selecciona imágenes claras y respetuosas.', 'Antes de publicarlas, verifica las autorizaciones de imagen aplicables y utiliza el canal del centro que corresponda.'],
    evidencia: 'Publicación o registro del grupo y periodo correctos, con la autorización de imagen verificada.',
    ejemplo: 'El coach prepara una foto del trabajo del grupo. Revisas las autorizaciones y la publicas por el canal correspondiente, sin datos personales innecesarios.',
    evitar: ['Reutilizar una foto antigua como si fuera de este mes.', 'Publicar sin revisar autorizaciones o mostrar documentos y datos personales de los niños.'],
    fuente: operativa,
    voz: voz('La foto debe mostrar una actividad real del grupo.', 'Antes de publicarla, revisa las autorizaciones de imagen y el canal que corresponde.', 'Cuida que no salgan documentos ni datos personales.', 'Una foto de otro mes no demuestra lo que hiciste en este periodo.'),
  },
  muro_informacion: {
    como: ['Revisa el muro de información del centro y actualiza horarios, convocatorias y avisos vigentes.', 'Retira lo vencido y comprueba que una familia pueda identificar qué ocurre, cuándo y cómo participar.'],
    evidencia: 'Muro visible, legible y actualizado, con fechas y datos consistentes con el calendario del centro.',
    ejemplo: 'Al anunciar la clase de padres colocas fecha, hora y lugar; después de realizarla retiras el aviso y mantienes la siguiente actividad vigente.',
    evitar: ['Acumular avisos vencidos que confunden a las familias.', 'Publicar información sin fecha o distinta de la que comunica recepción.'],
    fuente: operativa,
    voz: voz('Mira el muro como si fueras una familia que acaba de entrar.', 'Debe quedar claro qué actividad viene, cuándo es y cómo participar.', 'Retira los avisos vencidos y verifica que recepción maneje la misma información.', 'Un muro lleno de papeles viejos puede confundir más de lo que ayuda.'),
  },
  bienvenida: {
    como: ['Prepara la bienvenida de los grupos o ingresos que correspondan al periodo y publícala en el canal autorizado del centro.', 'Comprueba nombres, grupo e información útil para el inicio; revisa las autorizaciones si incluyes fotos.'],
    evidencia: 'Bienvenida publicada para los ingresos del periodo, con información correcta y accesible a sus representantes.',
    ejemplo: 'Al comenzar un grupo publicas un mensaje de bienvenida con su horario y los materiales que deben llevar, sin exponer teléfonos ni documentos.',
    evitar: ['Dar por publicada una bienvenida que quedó en borrador.', 'Confundir grupos o reutilizar nombres, horarios y fotos sin revisar.'],
    fuente: operativa,
    voz: voz('La bienvenida ayuda a que una familia sepa cómo empezar.', 'Revisa el grupo, el horario y lo que necesita llevar.', 'Después comprueba que el mensaje quedó publicado en el canal correcto.', 'Un borrador todavía no llega a nadie. Y los datos personales no van en una publicación abierta.'),
  },
  classdojo_activo: {
    como: ['Entra a ClassDojo y comprueba que los grupos vigentes estén operativos y tengan actividad del periodo.', 'Verifica que los responsables puedan publicar y dar seguimiento; resuelve accesos o grupos desactualizados.'],
    evidencia: 'Grupos vigentes accesibles, publicaciones del periodo y responsables que pueden trabajar en ellos.',
    ejemplo: 'Compruebas que el coach y la asistente pueden entrar al grupo activo y que su última retroalimentación corresponde a las clases de este mes.',
    evitar: ['Marcar Sí porque la aplicación está instalada.', 'Mostrar actividad de un grupo cerrado como prueba de que el actual está atendido.'],
    fuente: operativa,
    voz: voz('Tener ClassDojo instalado es apenas el acceso.', 'Comprueba que los grupos actuales tengan actividad y que sus responsables puedan trabajar.', 'Abre un grupo y revisa las publicaciones del periodo.', 'Si solo encuentras actividad de un grupo cerrado, todavía falta resolver el actual.'),
  },
  ninos_completos_classdojo: {
    como: ['Compara el listado de cada grupo activo con las fichas de niños en ClassDojo.', 'Agrega o corrige las fichas que falten y revisa duplicados y asignaciones incorrectas conservando el historial.'],
    evidencia: 'Listado del grupo conciliado con ClassDojo, niño por niño, sin faltantes ni duplicados pendientes.',
    ejemplo: 'El grupo tiene 8 niños. Revisas los 8 nombres y sus fichas; detectas que uno aparece dos veces y otro aún no está registrado.',
    evitar: ['Revisar solo que el total sea parecido.', 'Confundir ficha creada con representante conectado: son dos criterios diferentes.'],
    fuente: operativa,
    voz: voz('Revisa las fichas niño por niño.', 'El total puede coincidir y aun así haber un duplicado y un niño que falta.', 'Comprueba nombres y grupo, y conserva el historial al corregir.', 'La ficha completa es un criterio. Que su representante esté conectado es otro.'),
  },
  calendario: {
    como: ['Actualiza el calendario con las clases, actividades y cambios confirmados del centro.', 'Publícalo en el canal correspondiente y comprueba que los horarios coincidan con lo que conocen familias y equipo.'],
    evidencia: 'Calendario vigente publicado, con fechas y cambios confirmados y comunicados.',
    ejemplo: 'Una clase cambia de fecha. Primero confirmas la nueva fecha, actualizas el calendario y comunicas el cambio a los representantes del grupo.',
    evitar: ['Dejar publicado el calendario del mes anterior.', 'Cambiar un horario únicamente en el calendario sin avisar a las personas afectadas.'],
    fuente: manual('Administradora · Módulo 1: calendario y asistencia en Drive'),
    voz: voz('El calendario tiene que mostrar lo que realmente va a ocurrir.', 'Revisa las clases, las actividades y los cambios confirmados.', 'Si mueves una fecha, actualiza el calendario y avisa a las familias afectadas.', 'Cambiarla en silencio no garantiza que nadie se haya enterado.'),
  },
  asistente_classdojo: {
    como: ['Comprueba que la asistente responsable tenga acceso a los grupos que atiende en ClassDojo.', 'Revisa que esté realizando sus tareas de comunicación y seguimiento, y resuelve pendientes de acceso o sustitución.'],
    evidencia: 'Acceso vigente de la responsable y atención de las tareas del periodo que le corresponden.',
    ejemplo: 'La asistente nueva ya puede entrar, revisó las invitaciones pendientes y dio seguimiento a los representantes que necesitaban ayuda.',
    evitar: ['Marcar Sí solo porque existe una cuenta a su nombre.', 'Compartir contraseñas o dejar consultas sin responsable cuando cambia la asistente.'],
    fuente: operativa,
    voz: voz('La asistente necesita acceso y tareas atendidas.', 'No basta con que exista una cuenta con su nombre.', 'Revisa que pueda entrar a sus grupos y resolver los pendientes que le corresponden.', 'Si hubo un cambio de persona, entrega los pendientes y habilita su propio acceso.'),
  },
  grupo_study: {
    como: ['Verifica que cada grupo que está operando tenga su registro correspondiente en Study.', 'Comprueba identificación, coach y nivel contra la operación real; corrige grupos faltantes o duplicados.'],
    evidencia: 'Grupos activos identificables en Study, con datos coherentes con el calendario y el responsable real.',
    ejemplo: 'Empieza un grupo el sábado. Antes de revisar el trabajo de sus niños, compruebas que el grupo esté creado en Study con el coach y nivel correctos.',
    evitar: ['Crear un grupo duplicado porque no buscaste el existente.', 'Dar por incluidos a todos los niños solo porque el grupo ya está creado.'],
    fuente: operativa,
    voz: voz('Primero comprueba que el grupo exista en Study.', 'Revisa su identificación, su nivel y el coach responsable.', 'Busca antes de crear, para evitar duplicados.', 'Y recuerda: tener el grupo creado no significa que todos sus niños ya estén registrados.'),
  },
  centro_buen_estado: {
    como: ['Recorre recepción, salones, baños y zonas de paso; revisa limpieza, orden y funcionamiento del equipo.', 'Resuelve las fallas o repórtalas al responsable con una acción concreta; protege cualquier área que no pueda usarse con seguridad.'],
    evidencia: 'Revisión del estado real del centro y atención de las incidencias; una falla pendiente no se considera resuelta solo por reportarla.',
    ejemplo: 'Detectas una silla rota: la retiras de uso y coordinas su sustitución. Verificas que el salón vuelva a estar listo para recibir al grupo.',
    evitar: ['Marcar Sí porque la recepción se ve limpia sin revisar el resto.', 'Ocultar desperfectos o mantener equipo dañado disponible para los niños.'],
    fuente: operativa,
    voz: voz('Recorre el centro completo, no solamente la recepción.', 'Revisa salones, baños, zonas de paso y equipo.', 'Si una silla está rota, retírala de uso y coordina su sustitución.', 'Reportar una falla ayuda a resolverla, pero todavía no significa que esté corregida.'),
  },
  aromatizante: {
    como: ['Comprueba que la recepción tenga el aromatizante en condiciones de uso y que el ambiente resulte agradable.', 'Revisa limpieza y ventilación; ajusta o retira el producto si provoca molestias y resuelve la causa de los malos olores.'],
    evidencia: 'Recepción limpia y ventilada, producto disponible y uso adecuado sin molestias detectadas.',
    ejemplo: 'El dispensador está vacío. Lo repones según sus indicaciones y verificas el ambiente; si hay mal olor por falta de limpieza, corriges primero esa causa.',
    evitar: ['Usar una fragancia intensa para tapar suciedad o humedad.', 'Dejar el producto al alcance de los niños o ignorar una molestia reportada.'],
    fuente: operativa,
    voz: voz('Revisa que el aromatizante esté en condiciones de uso.', 'Pero empieza por la limpieza y la ventilación.', 'Si hay un mal olor, resuelve su causa; no lo tapes con más fragancia.', 'Cuida que el producto no provoque molestias y quede fuera del alcance de los niños.'),
  },
  mesa_cafe: {
    como: ['Revisa que la mesa de café y té esté limpia, ordenada y con los insumos disponibles en buen estado.', 'Comprueba el funcionamiento del equipo y una ubicación que permita atender a los adultos sin exponer a los niños a bebidas calientes.'],
    evidencia: 'Mesa lista para el servicio, insumos vigentes, utensilios limpios y equipo funcionando.',
    ejemplo: 'Antes de recibir a las familias revisas agua, vasos e insumos. Retiras un producto vencido y ubicas las bebidas calientes lejos de la zona de juego.',
    evitar: ['Tener una mesa decorada pero sin insumos ni servicio disponible.', 'Dejar derrames, utensilios sucios o bebidas calientes al alcance de los niños.'],
    fuente: operativa,
    voz: voz('La mesa tiene que estar lista para servir, no solo para verse bonita.', 'Revisa limpieza, agua, vasos e insumos en buen estado.', 'Retira lo vencido y atiende cualquier derrame.', 'Ubica las bebidas calientes donde los niños no puedan alcanzarlas.'),
  },
  wifi_gratis: {
    como: ['Coloca un aviso legible del wifi para visitantes con las instrucciones que necesiten para conectarse.', 'Prueba la conexión desde un teléfono y confirma que se ofrece la red de invitados del centro.'],
    evidencia: 'Aviso visible y conexión de visitantes probada, con datos de acceso vigentes.',
    ejemplo: 'Lees el aviso y te conectas como lo haría un padre. Si la clave cambió, corriges el cartel y vuelves a probar.',
    evitar: ['Anunciar wifi disponible cuando nadie puede conectarse.', 'Publicar credenciales administrativas del router o de la red interna del equipo.'],
    fuente: operativa,
    voz: voz('Prueba el wifi como lo haría un representante.', 'Lee el aviso, entra a la red de invitados y comprueba que funcione.', 'Si cambió la clave, actualiza el cartel.', 'Comparte el acceso de visitantes, nunca las credenciales administrativas del equipo.'),
  },
  coach_estrella: {
    como: ['Revisa las evidencias del trabajo del mes con los criterios de reconocimiento acordados por el centro.', 'Realiza el reconocimiento y explica qué logro o conducta se está premiando para que el equipo pueda aprender de ello.'],
    evidencia: 'Reconocimiento del mes realizado, con el motivo concreto y las evidencias que lo respaldan.',
    ejemplo: 'Reconoces a una coach por su seguimiento consistente y sus acuerdos con las familias; explicas al equipo qué hizo y qué resultado produjo.',
    evitar: ['Elegir por afinidad personal o sin revisar evidencias.', 'Dejar el reconocimiento anunciado sin realizarlo o usarlo para humillar a otros coaches.'],
    fuente: operativa,
    voz: voz('El reconocimiento debe explicar qué trabajo estás valorando.', 'Revisa las evidencias del mes y los criterios acordados.', 'Por ejemplo: un seguimiento consistente que ayudó a atender a las familias.', 'Premia el trabajo demostrado, no la afinidad personal ni la comparación que humilla a otro coach.'),
  },
  reuniones_mensuales: {
    como: ['Convoca la reunión mensual del equipo con una agenda de resultados, organización y asuntos que necesitan resolverse.', 'Realiza la reunión y deja acuerdos con responsable y fecha. Según el manual, coordina el calendario para que no coincida con la reunión trimestral.'],
    evidencia: 'Agenda, reunión realizada y acuerdos del mes con seguimiento; convocatoria sola no demuestra realización.',
    ejemplo: 'Revisan ausencias repetidas y acuerdan quién contacta a las familias y para cuándo. En la siguiente revisión comprueban si se hizo.',
    evitar: ['Contar una conversación informal sin acuerdos como la reunión del mes.', 'Repetir pendientes sin responsable ni fecha o convocar sin revisar el calendario trimestral.'],
    fuente: manual('Administradora · Módulo 7: reuniones mensuales y trimestrales con el equipo'),
    voz: voz('Llega a la reunión con una agenda concreta.', 'Revisa resultados y sal con acuerdos: quién hace qué y para cuándo.', 'Después comprueba si se cumplió.', 'Reunirse y repetir los mismos pendientes no los resuelve. Coordina también el calendario con la reunión trimestral.'),
  },
  monitoreo_camaras: {
    como: ['El responsable autorizado comprueba que las cámaras funcionen y realiza la revisión operativa que corresponda al centro.', 'Si detecta una incidencia, la registra y la atiende por el canal autorizado, limitando el acceso a las imágenes.'],
    evidencia: 'Registro de revisión y atención de incidencias, sin adjuntar ni divulgar grabaciones en el checklist.',
    ejemplo: 'Durante una revisión autorizada detectas una zona sin imagen. Reportas la falla y verificas su reparación; registras el resultado sin circular el video.',
    evitar: ['Marcar Sí porque las cámaras están instaladas sin comprobarlas.', 'Compartir grabaciones por grupos o usar imágenes de niños y trabajadores fuera de su finalidad autorizada.'],
    fuente: operativa,
    voz: voz('Instalar cámaras no es lo mismo que revisarlas.', 'El responsable autorizado debe comprobar que funcionen y atender las incidencias.', 'Si una zona no tiene imagen, reporta la falla y verifica su reparación.', 'Deja registro de la revisión. No necesitas circular las grabaciones para demostrar que lo hiciste.'),
  },
  actividades_equipo: {
    como: ['Organiza la actividad de integración o aprendizaje que corresponda al calendario del equipo, con un propósito claro.', 'Realízala y revisa con el equipo qué aprendieron o qué acuerdo van a aplicar en su trabajo.'],
    evidencia: 'Actividad realizada según el calendario acordado, participación y resultado o acuerdo que produjo.',
    ejemplo: 'El equipo practica cómo recibir una consulta difícil de un representante y acuerda cuándo intervenir y cuándo escalar a la administradora.',
    evitar: ['Marcar una actividad futura como realizada.', 'Confundir una foto de convivencia con evidencia de que se trabajó el propósito previsto.'],
    fuente: manual('Administradora · Módulo 7: integración y aprendizaje en las reuniones del equipo'),
    voz: voz('Define para qué van a realizar la actividad.', 'Puede ser practicar cómo atender una consulta difícil de un representante.', 'Después de hacerla, acuerden qué van a aplicar en el centro.', 'Una fecha en el calendario todavía no es una actividad realizada.'),
  },
  encuestas_equipo: {
    como: ['Coordina con el supervisor inmediato el trimestre de aplicación dentro del semestre y el listado completo del equipo convocado.', 'La encuesta debe ser anónima y sus resultados solo los revisa ese supervisor. Para darla por cumplida debe responder el 100% del equipo dentro del trimestre de aplicación.'],
    evidencia: 'Confirmación global del supervisor de participación completa, separada de las respuestas. Este criterio todavía se registra manualmente; la encuesta anónima del equipo aún no está disponible en la plataforma.',
    ejemplo: 'Si el equipo convocado tiene 6 integrantes, hacen falta 6 participaciones dentro del trimestre. Con 5 no está cumplida. El supervisor confirma el total sin revelar quién escribió cada opinión.',
    evitar: ['Usar la encuesta de familias o su meta de más del 50% para evaluar al equipo.', 'Pedir nombres en las respuestas, circular comentarios individuales o marcar Sí sin la confirmación del supervisor.'],
    fuente: { tipo: 'definicion', referencia: 'Regla indicada por Dirección: semestral, anónima, supervisor inmediato y participación total; calendario pendiente de definición' },
    voz: voz('La encuesta del equipo es semestral y debe ser anónima.', 'Solo el supervisor inmediato revisa sus resultados.', 'Debe responder todo el equipo dentro del trimestre acordado. Si son seis, necesitas las seis participaciones.', 'Esta encuesta todavía no está disponible en la plataforma. La casilla sigue siendo manual, con confirmación del supervisor.'),
  },
  meta_cobranza: {
    como: ['Revisa el registro de cuotas vencidas de cada mes y contrástalo con los pagos realmente recibidos.', 'Da seguimiento a las cuentas pendientes y registra correctamente los cobros. El sistema compara los datos del trimestre con la meta mostrada.'],
    evidencia: 'Pagos y cuotas vencidas conciliados en su fuente de registro; la meta se calcula, no se elige con Sí o No.',
    ejemplo: 'Si la meta visible permite hasta 3 vencidas y un mes registra 4, ese mes queda fuera de meta. Contactar a las familias ayuda, pero la deuda sigue pendiente hasta regularizarse.',
    evitar: ['Reducir las vencidas sin que exista un cobro o corrección sustentada.', 'Confundir una promesa de pago con un pago recibido o intentar compensar la meta con otras casillas.'],
    fuente: plataforma,
    voz: voz('La cobranza se demuestra con pagos y registros conciliados.', 'Una promesa de pago todavía es un pendiente.', 'Revisa las cuotas vencidas de cada mes y compáralas con la meta que muestra la pantalla.', 'Si encuentras un error, corrige su registro de origen. La meta se calcula con esos datos.'),
  },
  meta_desercion: {
    como: ['Revisa los retiros del periodo, sus fechas y los graduados por separado para que el sistema calcule la deserción real.', 'Trabaja las causas con el equipo: ausencias, avance, atención o acuerdos con las familias. Contrasta el resultado con la meta mostrada.'],
    evidencia: 'Retiros y graduaciones registrados correctamente, base de niños al inicio y cálculo del periodo visible.',
    ejemplo: 'Un niño termina el programa y otro se retira antes de concluir. Registras el primer caso como graduación y el segundo como retiro; los graduados no penalizan la deserción real.',
    evitar: ['Borrar a un retirado o cambiar la fecha para esconder una baja.', 'Registrar un retiro como graduación o asumir que una actividad de retención ya garantiza cumplir la meta.'],
    fuente: plataforma,
    voz: voz('Separa una graduación de un retiro.', 'El niño que terminó el programa no penaliza la deserción real.', 'Registra cada caso con su fecha y trabaja las causas de las bajas con el equipo.', 'No borres al retirado para mejorar el número. La meta tiene que reflejar lo que pasó.'),
  },
  meta_nuevos_ingresos: {
    como: ['Revisa que las nuevas inscripciones del periodo estén registradas correctamente, con su grupo y sus fechas reales.', 'Trabaja el seguimiento desde la consulta hasta la matrícula y compara el resultado calculado con la meta visible del periodo.'],
    evidencia: 'Inscripciones válidas del periodo y cálculo de ventas del trimestre; la plataforma deriva esta meta desde la base.',
    ejemplo: 'Una clase de prueba recibe 8 asistentes y se matriculan 3. Registras 3 nuevos ingresos; los otros 5 siguen en seguimiento y todavía no son ventas.',
    evitar: ['Contar interesados o asistentes a clase de prueba como matriculados.', 'Duplicar niños o mover fechas para alcanzar la meta; las actividades de soporte no sustituyen los ingresos.'],
    fuente: plataforma,
    voz: voz('Un interesado todavía no es un nuevo ingreso.', 'Si a una clase de prueba llegan ocho y se matriculan tres, registras tres.', 'A los otros cinco les das seguimiento.', 'Revisa las inscripciones y sus fechas reales. El sistema calcula el resultado y lo compara con la meta del periodo.'),
  },
}
